name: Main Workflow

on: [push]

jobs:
  run-custom-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Print Name Action
        uses: ./.github/actions/print-name
        with:
          name: 'Venkatesh'
